lib/deusexlog_web/router.ex
defmodule DeusexlogWeb.Router do
  use DeusexlogWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :auth do
    plug Deusexlog.UserManager.Pipeline
  end

  pipeline :ensure_auth do
    plug Guardian.Plug.EnsureAuthenticated
  end

  pipeline :guardian do
    plug DeusexlogWeb.Authentication.Pipeline
  end

  # Maybe logged in scope
  scope "/", DeusexlogWeb do
    pipe_through [:browser, :auth]

    get "/", PageController, :index

    get "/login", SessionController, :new
    post "/login", SessionController, :login
    get "/logout", SessionController, :logout
    get "/articles", ArticleController, :index
    get "/article/:slug", ArticleController, :show
  end

  # Definitely logged in scope
  scope "/", DeusexlogWeb do
    pipe_through [:browser, :auth, :ensure_auth]

    # get "/admin", AdminController, :index
    get "/user", CurrentUserController, :show
    patch "/user/:id", CurrentUserController, :update
    put "/user/:id", CurrentUserController, :update
    get "/user/edit", CurrentUserController, :edit
    resources "/users", UserController
    resources "/comments", CommentController
    resources "/posts", PostController
  end

  scope "/", DeusexlogWeb do
    pipe_through [:browser, :guardian]

    get "/admin", AdminController, :index

    get "/register", RegistrationController, :new
    post "/register", RegistrationController, :create
    get "/login", SessionController, :new
  end

  # Other scopes may use custom stacks.
  # scope "/api", DeusexlogWeb do
  #   pipe_through :api
  # end
end

lib/deusexlog_web/views/layout_view.ex
defmodule DeusexlogWeb.LayoutView do
  use DeusexlogWeb, :view
end

lib/deusexlog_web/templates/layout/admin.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title><%= Deusexlog.Application.site_name_data %></title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script src="<%= Routes.static_path(@conn, "/js/app.js") %>" ></script>
  </head>
  <body>
    <header>
      <h1 class="title"><%= Deusexlog.Application.site_name_data %></h1>
    </header>
    <nav role="navigation">
      <%= link "Home", to: Routes.page_path(@conn, :index) %>
      <%= link "Users", to: Routes.user_path(@conn, :index) %>
      <%= link "Post", to: Routes.post_path(@conn, :index) %>
      <%= link "Articles", to: Routes.article_path(@conn, :index) %>
      <%= link "Admin", to: Routes.admin_path(@conn, :index) %>
      <%= link "Logout", to: Routes.session_path(@conn, :logout) %>
      <%# link "Admin #{@current_user.username}", to: Routes.current_user_path(@conn, :show) %>
    </nav>
    <div>
      <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
      <script src="https://uicdn.toast.com/editor/latest/toastui-editor-all.min.js"></script>
      <script>
        const Editor = toastui.Editor;
      </script>
      <main role="main" class="container">
        <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
        <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
        <%= render @view_module, @view_template, assigns %>
      </main>
    </div>
  </body>
</html>

lib/deusexlog_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title><%= Deusexlog.Application.site_name_data %></title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <header>
      <h1 class="title"><%= Deusexlog.Application.site_name_data %></h1>
    </header>
    <nav role="navigation">
      <%= link "Home", to: Routes.page_path(@conn, :index) %>
      <%= link "Articles", to: Routes.article_path(@conn, :index) %>
      <%= link "Login", to: Routes.session_path(@conn, :login) %>
    </nav>
    <div>
      <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
      <main role="main" class="container">
        <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
        <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
        <%= render @view_module, @view_template, assigns %>
      </main>
    </div>
  </body>
</html>

lib/deusexlog_web/templates/layout/user.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title><%= Deusexlog.Application.site_name_data %></title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <header>
      <h1 class="title"><%= Deusexlog.Application.site_name_data %></h1>
    </header>
    <nav role="navigation">
      <%= link "Home", to: Routes.page_path(@conn, :index) %>
      <%= link "Post", to: Routes.post_path(@conn, :index) %>
      <%= link "Articles", to: Routes.article_path(@conn, :index) %>
      <%= link "Logout", to: Routes.session_path(@conn, :logout) %>
      <%= link "User #{@current_user.username}", to: Routes.current_user_path(@conn, :show) %>
    </nav>
    <main role="main" class="container">
      <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
      <script src="https://uicdn.toast.com/editor/latest/toastui-editor-all.min.js"></script>
      <script>
        const Editor = toastui.Editor;
      </script>
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= render @view_module, @view_template, assigns %>
    </main>
  </body>
</html>